#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/space.h"
#include "images/spaceship.h"
#include "images/asteroid1.h"
#include "images/asteroid2.h"
#include "images/asteroid3.h"
#include "images/blacksquare.h"
#include "images/spacestation.h"
#include "images/explosion.h"
#include "images/explodingspaceship.h"
#include "images/winscreen.h"
#include "images/spaceshipLARGE.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};
void delay(int n) {
  volatile int x = 0;
  for (int i=0; i<n*8000; i++)
    x++;
}

int main(void) {
  /* TODO: */
    // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;


  struct asteroid obstacles[10] = {
    {20, 10, 0, 0, 2},
    {70, 20, 0, 0, 1},
    {100, 190, 0, 0, 3},
    {120, 80, 0, 0, 2},
    {70, 100, 0, 0, 3},
    {120, 150, 0, 0, 1},
    {60, 60, 0, 0, 2},
    {60, 140, 0, 0, 3},
    {110, 40, 0, 0, 1},
    {40, 210, 0, 0, 2}
  };
  int oblen = sizeof(obstacles) / sizeof(obstacles[0]);
  for (int i = 0; i < oblen; i++) {
    if (obstacles[i].type == 1) {
      obstacles[i].height = ASTEROIDNEW_HEIGHT;
      obstacles[i].width = ASTEROIDNEW_WIDTH;
    } else if (obstacles[i].type == 2) {
      obstacles[i].height = ASTEROID2_HEIGHT;
      obstacles[i].width = ASTEROID2_WIDTH;
    } else if (obstacles[i].type == 3) {
      obstacles[i].height = ASTEROID_HEIGHT;
      obstacles[i].width = ASTEROID_WIDTH;
    }
  }
  struct player p = {148, 110, SPACESHIP_HEIGHT, SPACESHIP_WIDTH, 2, 2};
  struct spacestation goal = {0, 80, SPACESTATION_WIDTH, SPACESTATION_HEIGHT};


  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  unsigned int count = 0;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    switch (state) {
      case START:
        p.row = 148;
        p.col = 110;
        p.height = SPACESHIP_HEIGHT;
        p.width = SPACESHIP_WIDTH;
        p.uvel = 2;
        p.hvel = 2;

        waitForVBlank();
        if (count == 0) {
          drawFullScreenImageDMA(space);
          drawImageDMA(20, 80, SPACESHIPLARGE_WIDTH, SPACESHIPLARGE_HEIGHT, spaceshipLARGE);
        }
        drawCenteredString(120, 120, 0, 0, "Prepare to play space hero!", 0xFFFF);
        drawCenteredString(140, 120, 0, 0, "(Press START to continue)", 0xFFFF);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
          vBlankCounter = 0;
          count = 0;
          previousButtons = BUTTONS;
          break;
        }
        previousButtons = BUTTONS;
        count++;
        break;
      case PLAY:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          count = 0;
          previousButtons = BUTTONS;
          break;
        }
        int prevrow = p.row;
        int prevcol = p.col;
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          p.row -= p.uvel;
          if (p.row < 0) {
            p.row = 0;
          }
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          p.row += p.uvel;
          if (p.row > HEIGHT - p.height) {
            p.row = HEIGHT - p.height;
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          p.col -= p.hvel;
          if (p.col < 0) {
            p.col = 0;
          }
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          p.col += p.hvel;
          if (p.col > WIDTH - p.width) {
            p.col = WIDTH - p.width;
          }
        }
        if ((SCORE_COL <= p.col + p.width && SCORE_COL + 60 - 1 >= p.col) && (SCORE_ROW <= p.row + p.height && SCORE_ROW + 10 - 1 >= p.row)) {
          p.col = prevcol;
          p.row = prevrow;
        }
        int collided = 0;
        for (int i = 0; i < oblen; i++) {
          if ((obstacles[i].col + 1 <= p.col + p.width && obstacles[i].col + obstacles[i].width - 1 >= p.col)
          && (obstacles[i].row + 1 <= p.row + p.height && obstacles[i].row + obstacles[i].height - 1 >= p.row)) {
            waitForVBlank();
            undrawImageDMA(p.row, p.col, p.width, p.height, blacksquare);
            //drawRectDMA(p.row, p.col, p.width, p.height, BLACK);
            drawImageDMA(p.row, p.col, EXPLOSION_WIDTH, EXPLOSION_HEIGHT, explosion);
            delay(100);
            state = LOSE;
            count = 0;
            previousButtons = BUTTONS;
            collided = 1;
            break;
          }
        }
        if ((goal.col + 2 <= p.col + p.width && goal.col + goal.width - 2 >= p.col)
          && (goal.row <= p.row + p.height && goal.row + goal.height - 2 >= p.row)) {
            delay(100);
            state = WIN;
            count = 0;
            previousButtons = BUTTONS;
            collided = 1;
            break;
          }
        if (collided) {
          break;
        }
        char buffer[50];
        int time = vBlankCounter / 6;
        sprintf(buffer, "Score: %d", time);
        waitForVBlank();
        if (count == 0) {
          fillScreenDMA(BLACK);
          for (int i = 0; i < oblen; i++) {
            if (obstacles[i].type == 1) {
              drawImageDMA(obstacles[i].row, obstacles[i].col, obstacles[i].width, obstacles[i].height, asteroidnew);
            } else if (obstacles[i].type == 2) {
              drawImageDMA(obstacles[i].row, obstacles[i].col, obstacles[i].width, obstacles[i].height, asteroid2);
            } else if (obstacles[i].type == 3) {
              drawImageDMA(obstacles[i].row, obstacles[i].col, obstacles[i].width, obstacles[i].height, asteroid);
            }
          }
          drawImageDMA(goal.row, goal.col, goal.width, goal.height, spacestation);
        } else {
          //fillScreenDMA(BLACK);
          undrawImageDMA(prevrow, prevcol, p.width, p.height, blacksquare);
          drawImageDMA(p.row, p.col, p.width, p.height, spaceship);
          undrawImageDMA(10, 180, 60, 10, blacksquare);
          drawString(10, 180, buffer, 0xFFFF);
        }
        count++;
        previousButtons = BUTTONS;
        break;
      case WIN:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          count = 0;
          previousButtons = BUTTONS;
          break;
        }
        waitForVBlank();
        if (count == 0) {
          drawFullScreenImageDMA(winscreen);
        } else {
          sprintf(buffer, "Final Score: %d", time);
          drawString(30, 150, "You win!", 0xFFFF);
          drawString(50, 130, buffer, 0xFFFF);
        }
        // state = ?
        count++;
        break;
      case LOSE:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
          count = 0;
          previousButtons = BUTTONS;
          break;
        }
        waitForVBlank();
        if (count == 0) {
          drawFullScreenImageDMA(explodingspaceship);
        } else {
          drawCenteredString(120, 120, 0, 0, "You Lost :(", 0xFFFF);
        }
        count++;
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }


  return 0;
}
